version: "3.9"
services:
  site:
    image: hiperstream/developers-portal:release
    build:
      target: release
      args:
        - NODE_ENV=production
        - SERVER_PORT=80
    ports:
      - 5050:80
