/* tslint:disable */
/* eslint-disable */
/**
 * Site API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ListRequest
 */
export interface ListRequest {
    /**
     * 
     * @type {number}
     * @memberof ListRequest
     */
    'skip'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListRequest
     */
    'take'?: number | null;
}

/**
 * SitePresentationApiApi - axios parameter creator
 * @export
 */
export const SitePresentationApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ListRequest} listRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSupportedLanguage: async (listRequest: ListRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listRequest' is not null or undefined
            assertParamExists('listSupportedLanguage', 'listRequest', listRequest)
            const localVarPath = `/v1/supported-language`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SitePresentationApiApi - functional programming interface
 * @export
 */
export const SitePresentationApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SitePresentationApiApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ListRequest} listRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSupportedLanguage(listRequest: ListRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSupportedLanguage(listRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SitePresentationApiApi.listSupportedLanguage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SitePresentationApiApi - factory interface
 * @export
 */
export const SitePresentationApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SitePresentationApiApiFp(configuration)
    return {
        /**
         * 
         * @param {ListRequest} listRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSupportedLanguage(listRequest: ListRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.listSupportedLanguage(listRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SitePresentationApiApi - object-oriented interface
 * @export
 * @class SitePresentationApiApi
 * @extends {BaseAPI}
 */
export class SitePresentationApiApi extends BaseAPI {
    /**
     * 
     * @param {ListRequest} listRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SitePresentationApiApi
     */
    public listSupportedLanguage(listRequest: ListRequest, options?: RawAxiosRequestConfig) {
        return SitePresentationApiApiFp(this.configuration).listSupportedLanguage(listRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



